### ISSUE TITLE
Redundant grave accent appears after completion quoted name

### ISSUE THREAD

**Issue by przepompownia** [lighttiger2505/sqls#35]
**Reproduction**
Assume that `logs` is the only table with name beginning with `l`, then write
```sql
SELECT * from `l---cursor here
```
After completion I get 
```sql
SELECT * FROM ``logs`
```

**Expected behavior**

```sql
SELECT * FROM `logs`
```

 - Debian sid
 - sqls Version:v0.2.0, Revision:6f977d8
**Additional context**
 - CoC nvim

Can you reproduce this bug?

**Comment by lighttiger2505** [comment]
This problem is not a bug in sqls, it is caused by a difference in the way sqls and completion manager recognize completion strings.

sqls is giving me completion suggestions without any problem, but the completion manager is not recognizing the first backtick as an inputted string. This problem doesn't occur in other languages because it is rare for a programming language to use backticks to decorate identifiers.

**Comment by przepompownia** [comment]
```vim
set iskeyword+=`
```
seems to be enough for `ft=sql`. I had similar problem some months ago and needed to find the time to recall it.
