### ISSUE TITLE
Run without a database connection

### ISSUE THREAD

**Issue by raxod502** [lighttiger2505/sqls#39]
**Is your feature request related to a problem? Please describe.**
I would like to use this language server to provide generic SQL autocompletion in an environment where I cannot guarantee the existence of a live database instance.

**Describe the solution you'd like**
It would be great if not having a configuration file meant that the language server would simply autocomplete generic SQL keywords. What currently happens is that the language server refuses to serve any completions, with the following error message:

```
Error: database cache not found
```

I believe this used to be the behavior of sqls, but it changed some releases ago.

**Comment by lighttiger2505** [comment]
In order to get the most out of sqls, it is ideal to start sqls with the correct configuration to get information about the DB schema. However, it is not desirable to lose all functions or get unnecessary error messages just because you cannot connect to the DB. This was a lack of consideration on my part.

I will fix it so that some of the functions of sqls can be used even if the DB cannot be connected.

**Comment by lighttiger2505** [comment]
https://github.com/lighttiger2505/sqls/commit/64b3884b1703974ec0825682db68c493b1ff165c

With this change, sqls now works with keyword completion even without a DB connection.

Also, there is still room for improvement in the keyword completion, and we plan to improve it in the future.

**Comment by raxod502** [comment]
Yay, thanks so much!
